name: Publish Docker Image

on: 
  release:
    branches: main
  workflow_dispatch:
    branches: main

env:
  LOG_LEVEL: info
  PORT: 3000
  NODE_ENV: test
  MONGO_DB: loubou97_notesdb
  DOCKER_IMAGE_NAME: noteapp
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  DOCKER_IMAGE_TAG: latest
  NAMESPACE: default
  DEPLOYMENT_FULL_PATH: k8s/prod/api-deployment.yaml
  SERVICE_FULL_PATH: k8s/services/api.yaml

jobs:
  Build:
      runs-on: ubuntu-latest
      name: Build the app
      steps:
        - uses: actions/checkout@v1
        - name: npm install
          run: |
            npm install
        - name: npm run compile
          run: |           
            npm run compile
        - uses: actions/upload-artifact@master
          with:
            name: dist aritiact
            path: dist/
  Build_Docker_Image: 
          runs-on: ubuntu-latest 
          needs: [Build]
          name: Build, Push Docker Image
          steps:
          - uses: actions/checkout@v1
          - name: download artifact
            uses: actions/download-artifact@master
            with:
              name: dist aritiact
              path: dist/
          - uses: pozetroninc/github-action-get-latest-release@master
            id: noteapp
            with:  
              repository: ${{ github.repository }}

          - name: Build and Publish head Docker image
            uses: VaultVulp/gp-docker-action@1.1.7
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }} 
              image-name: ${{env.DOCKER_IMAGE_NAME}} 
              image-tag: ${{steps.noteapp.outputs.release}}

